### ISSUE TITLE
Update webhook

### ISSUE THREAD

**Issue by leobalter** [qunitjs/qunitjs.com#130]
@jzaefferer @gnarf It looks like the webhook to publish new tags is failing since we moved to the qunitjs org. Help me, please!

**Comment by leobalter** [comment]
@jzaefferer @gnarf friendly ping. The website is 2 versions late. I'm lost.

**Comment by trentmwillis** [comment]
I believe this is resolved as we have been able to deploy successfully. If a deployment fails, you may need to retrigger from the "Settings > Webhooks" page.

**Comment by gnarf** [comment]
Yup, sorry, I should have mentioned it here when I fixed it!
