### ISSUE TITLE
Augment QUnit cookbook with Step API case study

### ISSUE THREAD

**Issue by platinumazure** [qunitjs/qunitjs.com#131]
Per [this comment](https://github.com/qunitjs/qunit/issues/1075#issuecomment-275149846), we should see if we can augment the QUnit Cookbook with a case study on the Step API (and how it can be useful for asynchronous and other complicated test cases).

This is not critical since we already have documentation in api.qunitjs.com for the feature-- just seems like a hugely worthwhile opportunity for a more narrative case study treatment of the feature.

**Comment by trentmwillis** [comment]
I've opened https://github.com/qunitjs/qunit/pull/1223 to address this. I'm not sure a narrative format would help much, but some compare/contrast examples and reworded documentation I think communicates the point effectively.
