### ISSUE TITLE
Nginx version disclosure via forbidden Page

### ISSUE THREAD

**Issue by Sajibekanti** [qunitjs/qunitjs.com#132]
Hello 
I am Sajibe kanti 
I Have Found A Bug on your Web .

Vulnerability : Nginx version disclosure via forbidden Page

This information might help an attacker gain a greater understanding of the systems in use and potentially develop further attacks targeted at the specific version of Nginx.

Impact: 
An attacker might use the disclosed information to harvest specific security vulnerabilities for the version identified.

Steps to reproduce:

Go to http://qunitjs.com/jquery-wp-content/themes/jquery/js/

Now the nginx version shows in bottom.

Reference : https://hackerone.com/reports/194319

Thanks 
Sajibe Kanti

**Comment by leobalter** [comment]
Thanks for the report. 

I have time scheduled to rework the docs and website in a couple weeks so this should be fixed then.

cc @gnarf

**Comment by Sajibekanti** [comment]
Did I Get Credit or Public Acknowledgement  ?

**Comment by gnarf** [comment]
Thanks for the report!

I did turn off the nginx versions for the site, cuz why expose them, however the server that renders that 403 message is not the same server that delivers the page to you, so this wasn't ever really a problem IMO.

As far as I know, we don't offer a bug bounty, but I will pay you kindly with my thanks! ❤️ 

Feel free to reference this issue for "public acknowledgement"

**Comment by Sajibekanti** [comment]
:) Great It Fixed

**Comment by platinumazure** [comment]
@qunitjs/qunit-team Do we have a procedure in place for private disclosures of (more serious) vulnerabilities? Public disclosures can be dangerous for more serious vulnerabilities, so I'm just wondering if we have an e-mail address or web form or something for those cases.

**Comment by gnarf** [comment]
> Do we have a procedure in place for private disclosures of (more serious) vulnerabilities?

Should probably update/advertise it for your own project, but we used to use security@jquery.com for this purpose.
