### ISSUE TITLE
Front page is outdated

### ISSUE THREAD

**Issue by gibson042** [qunitjs/qunitjs.com#133]
Looks like we need to deploy master:
> Current Release - v2.1.1
> * qunit-2.1.1.js
> * qunit-2.1.1.css

**Comment by trentmwillis** [comment]
I updated and pushed a new tag yesterday during the release, but the website did not deploy. I'm unsure why, especially since the API site deployed just fine. I've reached out to @leobalter since he was the last one to deploy the site.

**Comment by trentmwillis** [comment]
Figured out how to retrigger the webhook. Website is now correctly updated.

**Comment by leobalter** [comment]
Sorry for my late reaction. Thanks for solving it!
