### ISSUE TITLE
Migrate to GitHub Pages

### ISSUE THREAD

**Issue by trentmwillis** [qunitjs/qunitjs.com#143]
The current structure of this repo makes it difficult for new contributors. They have to get an entire VM running just to properly view their changes. So, I would like to propose that we migrate to a Jekyll site hosted on GitHub Pages. We did this somewhat recently with the API documentation.

The benefits as I see them are:
1. Easier for new contributors to get up and running
2. Documentation can be mostly written in Markdown, which means it can also be viewed in the repo itself
3. Less dependency on the jQuery infrastructure
4. Due to 3, we'll have more control over the look and feel of the website

**Comment by jzaefferer** [comment]
What's the story for searching Jekyll sites these days? Searching for "jekyll search" produces kinda random blog posts and tutorials. That's still my biggest gripe with static site generators...

**Comment by platinumazure** [comment]
For what it's worth, ESLint leverages algolia for site searching. Might be worth checking it out.

**Comment by Krinkle** [comment]
For the record, this is now being worked on at <https://github.com/qunitjs/qunitjs.github.io>.

Launch tracked at <https://github.com/qunitjs/qunitjs.github.io/issues/1>.
