### ISSUE TITLE
Add guide for CLI usage (Document --require)

### ISSUE THREAD

**Issue by jdalton** [qunitjs/qunitjs.com#144]
The `--require` option is fantastic.
I'm just opening an issue to track its docs inclusion.

Related to https://github.com/qunitjs/qunit/pull/1271.

**Comment by trentmwillis** [comment]
:+1: Brief documentation can be found by running `qunit --help`. That said, there's a larger task here of adding a section to the website for more thorough treatment of the Node/CLI side of using QUnit.

**Comment by Krinkle** [comment]
Done, at <https://qunitjs.com/cli/>. Ref https://github.com/qunitjs/qunitjs.com/commit/0a70d75535c8f5f75b388d9f78bc.
