### ISSUE TITLE
Recommend eslint-plugin-qunit on qunitjs.com

### ISSUE THREAD

**Issue by bmish** [qunitjs/qunitjs.com#174]
[eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) is a terrific linting plugin for enforcing best testing practices and autofixing common mistakes with QUnit tests, and there are thousands of apps using it already. It can help improve test quality as well as improve the developer experience of using QUnit.

We should find somewhere on qunitjs.com to recommend it. 

Here are some ideas for where to mention it:

1. [Plugins](https://qunitjs.com/plugins/) -- if it can be considered a qunit plugin, we can add the `qunit-plugin` keyword to the package so it shows up automatically
2. A new "Linting" guide page after "Plugins"
3. Somewhere else?

CC: @platinumazure

**Comment by Krinkle** [comment]
I think this would go well on the upcoming "Integrations" page, perhaps under a section for "Linting" indeed and/or a section for "Text editors and IDEs".
