### ISSUE TITLE
Is there a forum for qunitjs + question?

### ISSUE THREAD

**Issue by MozgC** [qunitjs/qunitjs.com#181]
Hello,
Is there a dedicated forum for qunitjs or we should use issues here on github?

Anyway, here's my question:

This is my first-ever javascript/html test.
I need to test my function on multiple html inputs.
For example see:
https://github.com/MozgC/chess.com/blob/main/QUnit/test.html &
https://github.com/MozgC/chess.com/blob/main/QUnit/test3.html

As you can see, there's a lot of code duplication at the beginning of html files.
How can avoid this duplication? <--- MAIN QUESTION

Let's say I need to test my getPgn() function on 10 different htmls and get 10 different returned values.
You can see I tried to load html for a 2nd test here:
https://github.com/MozgC/chess.com/blob/main/QUnit/test.html#L22
But it doesn't work

**Comment by Krinkle** [comment]
> Hello,
> Is there a dedicated forum for qunitjs or we should use issues here on github?

We have a support chat at <https://gitter.im/qunitjs/qunit>.

You can also try creating an issue at https://github.com/qunitjs/qunit/issues, but the chat is usually faster for questions.

I'll close this issue for now as I see you already found the chat meanwhile. (Note that this repo is for the website.)
