### ISSUE TITLE
Document integrations with various CI environments

### ISSUE THREAD

**Issue by jzaefferer** [qunitjs/qunitjs.com#42]
Covering how to integrate QUnit with various CI environments:
 
- Jenkins, Travis, CircleCI
- BrowserStack, Sauce Labs, testling
- <s>TestSwarm</s>
- <s>PhantomJS</s>
- testem, testacular
- Karma
- Grunt
- Gulp

But also other environments:
- [ ] getting files with bower or npm (#40)
- [ ] using directly or with AMD (#50)

**Comment by Krinkle** [comment]
Perhaps also a minimal example running via Headless Chromium (possibly via Puppeteer).

**Comment by Krinkle** [comment]
Grunt / Headless Chrome:
<https://github.com/gruntjs/grunt-contrib-qunit/issues/171>

**Comment by Krinkle** [comment]
DevExpress: https://github.com/DevExpress/testcafe

**Comment by Krinkle** [comment]
https://github.com/qunitjs/qunitjs.com/commit/30f316fdf0c57722b8393de70ae094ca639e015e
